# Generated by Django 6.0.3 on 2026-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_plato'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(default='Delicioso plato'),
        ),
        migrations.AddField(
            model_name='plato',
            name='empresa',
            field=models.CharField(default='Restaurante X', max_length=100),
        ),
        migrations.AddField(
            model_name='plato',
            name='ingredientes',
            field=models.TextField(default='Ingredientes varios'),
        ),
    ]
