# Generated by Django 6.0.3 on 2026-04-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_ingrediente_remove_plato_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='plato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='usuarios.plato'),
            preserve_default=False,
        ),
    ]
