# Generated by Django 6.0.3 on 2026-04-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_plato_ingredientes_ingrediente_plato'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ci',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ubicacion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
