# Generated by Django 6.0.3 on 2026-04-18 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_pedido_ci_pedido_nombre_cliente_pedido_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDetalleIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='usuarios.pedidodetalle')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ingrediente')),
            ],
        ),
    ]
