# Generated by Django 6.0.3 on 2026-04-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuario_foto_usuario_telefono_usuario_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena'), ('Frutas', 'Frutas'), ('Vegetales', 'Vegetales'), ('Proteínas', 'Proteínas')], max_length=50),
        ),
    ]
